# Generated by Django 4.0.5 on 2022-06-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0003_remove_customer_car_number_driver_car_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='car_number',
            new_name='car',
        ),
    ]
