# Generated by Django 4.0.5 on 2022-06-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0005_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upgated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.driver')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_app.orderstatus')),
            ],
        ),
    ]
